---
- hosts: jboss
  remote_user: deployuser
  gather_facts: false
  vars:
    app_play: 'NO APLICA'
  tasks:
    - name: Tareas a en PLAY reservado
      shell:
        cmd: echo Tareas a en PLAY
  roles:
    - deploy_jboss

---
- hosts: jboss
  remote_user: deployuser
  gather_facts: false
  vars:
    app_play: 'NO APLICA'
  tasks:
    - name: Tareas a en PLAY reservado
      shell:
        cmd: echo Tareas a en PLAY
  roles:
    - role: deploy_jboss
      tasks_from: copy.yml #para transferir y eliminar ok
