#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy_micros

- name: Template script shell install_app_jboss.sh para desplegar app jboss {{servidor}}
  ansible.builtin.template:
    src: /ansible/deploy_microservicios/templates/template_micros.sh
    dest: /home/deployuser/bin/template_micros_{{cambio}}.sh
    owner: deployuser
    group: deployuser
    mode: '0755'

- name:  calcul치ndo  ejecuci칩n remota
  debug:
    msg: |
      now_datetime: {{ now_datetime }}
      at_datetime: {{at_datetime}}
      at_seconds: {{at_seconds}}
      at_minutes: {{at_minutes}}

- name: programando ejecucion
  ansible.posix.at:
    #script_file: /home/deployuser/bin/install_app_jboss_{{cambio}}.sh > /home/deployuser/log/{{cambio}}.log
    command: SHELL=/bin/bash /home/deployuser/bin/template_micros_{{cambio}}.sh > /home/deployuser/logs/log_ejecucion_{{cambio}}.log
    count: "{{ at_minutes }}"
    units: minutes
  #become: true

- name: Verificando programaci칩n.
  command: at -l
  register: out

- name: Muestra programaci칩n at-l
  debug:
    var: out.stdout
